FROM golang:1.24-alpine
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY proxy.go sch.go ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o proxy_bin .
RUN chmod +x ./proxy_bin
EXPOSE 8080
CMD ["./proxy_bin"]
