FROM golang:1.24-alpine
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY forumDest.go sch.go ./
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o forum_bin .
RUN chmod +x ./forum_bin
CMD ["./forum_bin"]
